### ISSUE TITLE
After pair lametric show as unavailable

### ISSUE THREAD

**Issue by mruiter** [balmli/com.lametric.time#3]
Logged in on with my developers account onto the lametric pages you get directed to .
All looks well , finds the lametrics and they get added as devices

They show up as unreachable straight away .
Also a repair doesn’t change anything and they keep unavailable

![9562EE65-8006-4CF9-BBA2-D25839E87368](https://user-images.githubusercontent.com/17739535/96304653-c539b200-0ffc-11eb-999f-22bff87cd4ef.png)

**Comment by balmli** [comment]
I guess that's the env.json file missing with client and client secret.

You can install the app directly from the Homey Community Store:
https://store.homey.community/app/com.lametric.time
and that should fix the issue.

Later the app might be available in the Athom app store as well

**Comment by mruiter** [comment]
Did the remove app . Reboot honey . Reinstall from community store and still the same error .

I did it remotely so running debug from cli is not possible . But I guess without the api Ids it’s not 123 for me to run it by cli to debug or is there a way I can get the api keys in the app myself and run cli ?

Verstuurd vanaf mijn iPhone

**Comment by balmli** [comment]
I can send you the file.  Email or you on the Homey community ?  Or Slack?

**Comment by mruiter** [comment]
I’m on normal athom slack and the community slack . My name is Lolo Maserati on both 

Verstuurd vanaf mijn iPhone

**Comment by balmli** [comment]
In the last version, 0.9.2, the UPnP SSDP discovery has been removed, and that solved the issue for at least one other user.

**Comment by balmli** [comment]
You can install the app from the Homey Community Store: https://store.homey.community/app/com.lametric.time

**Comment by mruiter** [comment]
Can confirm solved here also 👌

Verstuurd vanaf mijn iPhone
